version: "3.8"
services:
  myportfolio:
    container_name: myportfolio
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - MYSQL_HOST=mysql
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mariadb:10.6
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql

volumes:
  mydatabase: